def createTable(connection, req):
    try:
        string = "CREATE TABLE "
        string = string + req["tableName"] + " (Serial BIGINT GENERATED BY DEFAULT AS IDENTITY, "

        for key, value in req["attributes"].items():
            string = string + key
            string = string + " " + value + ", "
        
        string = string.rstrip(string[-1])
        string = string.rstrip(string[-1])
        string = string + ")"
        
        cursor = connection.cursor()
        cursor.execute(f"{string}")

    except Exception as err:
        raise ValueError (f"{err}") from None



# constraint = "ALTER TABLE "
# constraint = constraint + req["tableName"] + " ADD CONSTRAINT " + req["tableName"] + "_pk PRIMARY KEY (" + req["pk"] + ")"
# cursor.execute(f"{constraint}")